# Generated by Django 3.2.9 on 2022-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_rename_author_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/users', verbose_name='Изображение профиля'),
        ),
    ]
