# Generated by Django 3.2.9 on 2022-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20220202_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Изображение профиля'),
        ),
    ]
