# Generated by Django 3.2.9 on 2022-02-22 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 51, 9, 18039), verbose_name='Время создание'),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 51, 9, 18039), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 51, 9, 18039), verbose_name='Время создание'),
        ),
    ]
