# Generated by Django 3.2.9 on 2022-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_auto_20220222_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создание'),
        ),
    ]
