# Generated by Django 3.2.9 on 2022-02-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_auto_20220222_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
