# Generated by Django 3.2.9 on 2022-02-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0015_delete_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
