# Generated by Django 3.2.9 on 2022-03-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0017_auto_20220308_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
